### ISSUE TITLE
Support for Anycubic Photon?

### ISSUE THREAD

**Issue by McNugget6750** [Andrew-Dickinson/photonic-etcher#1]
This is an amazing project! While you're at Anycubic models, would the (original) Photon be easy to implement? It's not a mono but the resolution should still be plenty for all hobby grade boards.

**Comment by Andrew-Dickinson** [comment]
Hey,

Happy to see interest in this project :) 

The original photon (`.pws` file format) has a slightly different image encoding to the later printer models. I don't think it would be too challenging to implement, but will take me a bit to put together.  I'll take a look next weekend if I have a chance, otherwise feel free to bump this thread to remind me.

One thing I may need help with is validation of some test files to be sure that the printer can parse them and that they display appropriately, but I'll drop them here if/when that's needed.

**Comment by Andrew-Dickinson** [comment]
@McNugget6750 I'm excited to announce that `photonic-etcher` now supports `.pws` file export. You should see the option if you download the latest offline version (1.1.0), or refresh the website

**Comment by Andrew-Dickinson** [comment]
Please let me know if the files work on your printer, I only have the one printer to test with

**Comment by Andrew-Dickinson** [comment]
Closing this for now, since this was shipped with the `1.1.0` release. Please open an issue if you encounter any challenges when using the newly added printer options.
