### ISSUE TITLE
Support for Anycubic Photon Mono

### ISSUE THREAD

**Issue by dankris1603** [Andrew-Dickinson/photonic-etcher#3]
Hi, amazing project! could you please make it compatible with the Anycubic Photon Mono?

**Comment by daxliniere** [comment]
I have my fingers crossed that someone will get on board and help create a version for all Chitu printers. (Elegoo, etc)

**Comment by Andrew-Dickinson** [comment]
Hey folks,

Happy to see interest in this project. I believe the Photon Mono format is extremely similar to the Mono SE format (due to the extremely similar printer designs). You may literally be able to rename the files from `.pwms` to `.pwmo` and have it print. If you're brave enough to give this a try, go ahead (I don't personally have a Mono to try this on). Otherwise I'll take a look at this next weekend and try to add some of the "low hanging fruit" of other Anycubic printer models with similar formats.

Feel free to bump this thread in a few weeks if I get distracted and forget to look at this.

**Comment by Andrew-Dickinson** [comment]
@dankris1603  I'm excited to announce that photonic-etcher now supports `.pwmo` file export. You should see the option if you download the latest offline version (1.1.0), or refresh the website.

Please let me know if the new file format works on your printer. The files for the other printers look correct to me, but I only have one printer to test with.

**Comment by Andrew-Dickinson** [comment]
Closing this for now, since this was shipped with the `1.1.0` release. Please open an issue if you encounter any challenges when using the newly added printer options.

**Comment by dankris1603** [comment]
oh amazing! I'll test it and return the feedback
