### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lekasl** [Andrew-Dickinson/photonic-etcher#4]
Hello. 
I have a error when open file. 
Can you help me ?
Thank you.
![error](https://user-images.githubusercontent.com/92690154/185183374-c9e6a5cb-0561-400a-be52-a15edcf67b16.PNG)

**Comment by Andrew-Dickinson** [comment]
Can you send me the gerber file you're trying to use? Either a link here or email it to me (my email is in my bio)

**Comment by Andrew-Dickinson** [comment]
Also any other context about where this file came from. What software was used to generate it, which options were used, etc

**Comment by Lekasl** [comment]
Hello.
I use a SprintLayout. I can send it if you want.
All my files can't open in your software.

**Comment by Lekasl** [comment]
Do you received my Gerber file ?
[PCB.zip](https://github.com/Andrew-Dickinson/photonic-etcher/files/9365309/PCB.zip)

**Comment by Andrew-Dickinson** [comment]
Lekasl,

It appears you didn't export the board outline layer. This is required so that photonic etcher can determine the size and extents of the PCB. I also recommend you export the drill layers. Really there isn't much downside to exporting everything and then filtering within photonic-etcher to the layers that you want.

Here's some detailed instructions for doing this export with SprintLayout: https://support.jlcpcb.com/article/67-how-to-export-sprint-layout-pcb-to-gerber-files

**Comment by Andrew-Dickinson** [comment]
Closing this issue for now. Please re-open if you are still having issues
